# Generated by Django 5.2.7 on 2025-10-15 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafile',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='updated_at',
        ),
    ]
