# Generated by Django 5.2.7 on 2025-10-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_rename_created_at_mediafile_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
