# Generated by Django 5.2.7 on 2025-10-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_mediafile_size_alter_mediafile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
