# Generated by Django 5.2.7 on 2025-10-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_mediafile_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='converted_video',
            field=models.FileField(blank=True, null=True, upload_to='converted_videos/'),
        ),
    ]
